#pragma once

/* Shared IOCTL definitions — Guardian.sys + usermode controller */

#ifdef _KERNEL_MODE
#include <ntddk.h>
#include <wdm.h>
#else
#include <windows.h>
#endif

#include "../structures/guardian_state.h"
#include "../structures/app_policy.h"
#include "../structures/route_assignment.h"
#include "../structures/killswitch.h"
#include "../structures/telemetry.h"
#include "../structures/dns.h"
#include "../protocol/guardian_message.h"

#define GUARDIAN_DEVICE_NAME L"\\Device\\WireSentinelGuardian"
#define GUARDIAN_SYMBOLIC_NAME L"\\DosDevices\\WireSentinelGuardian"
#define GUARDIAN_USER_DEVICE_PATH L"\\\\.\\WireSentinelGuardian"

#define GUARDIAN_IOCTL_DEVICE_TYPE 0x8010u

#define IOCTL_GUARDIAN_GET_DRIVER_STATE \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_GUARDIAN_SET_APP_POLICY \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GUARDIAN_SYNC_POLICIES \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GUARDIAN_SET_ROUTE \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GUARDIAN_CLEAR_ROUTE \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GUARDIAN_SYNC_ROUTES \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GUARDIAN_SET_KILL_SWITCH \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x806, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GUARDIAN_GET_TELEMETRY \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x807, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_GUARDIAN_EXPORT_STATE \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x808, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_GUARDIAN_IMPORT_STATE \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x809, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GUARDIAN_RECONCILE \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x80A, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GUARDIAN_DNS_SET_CONFIG \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x80B, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GUARDIAN_GET_PERF_STATS \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x80C, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_GUARDIAN_GET_DNS_STATS \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x80D, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_GUARDIAN_SET_GUARDIAN_MODE \
    CTL_CODE(GUARDIAN_IOCTL_DEVICE_TYPE, 0x80E, METHOD_BUFFERED, FILE_WRITE_DATA)

#define GUARDIAN_MAX_IOCTL_BUFFER (GUARDIAN_MAX_EXPORT_BYTES + GUARDIAN_MESSAGE_HEADER_SIZE)
