//! IOCTL codes and device path — mirrors `shared/protocol/guardian_ioctl.h`.

pub const GUARDIAN_USER_DEVICE_PATH: &str = "\\\\.\\WireSentinelGuardian";
pub const GUARDIAN_IOCTL_DEVICE_TYPE: u32 = 0x8010;
pub const GUARDIAN_PROTOCOL_VERSION: u32 = 1;

const FILE_READ_DATA: u32 = 0x0001;
const FILE_WRITE_DATA: u32 = 0x0002;
const METHOD_BUFFERED: u32 = 0;

const fn ctl_code(device_type: u32, function: u32, method: u32, access: u32) -> u32 {
    (device_type << 16) | (access << 14) | (function << 2) | method
}

pub const IOCTL_GUARDIAN_GET_DRIVER_STATE: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_READ_DATA);
pub const IOCTL_GUARDIAN_SET_APP_POLICY: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_GUARDIAN_SYNC_POLICIES: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_GUARDIAN_SET_ROUTE: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_GUARDIAN_CLEAR_ROUTE: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_GUARDIAN_SYNC_ROUTES: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_GUARDIAN_SET_KILL_SWITCH: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x806, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_GUARDIAN_GET_TELEMETRY: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x807, METHOD_BUFFERED, FILE_READ_DATA);
pub const IOCTL_GUARDIAN_EXPORT_STATE: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x808, METHOD_BUFFERED, FILE_READ_DATA);
pub const IOCTL_GUARDIAN_IMPORT_STATE: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x809, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_GUARDIAN_RECONCILE: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x80A, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_GUARDIAN_DNS_SET_CONFIG: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x80B, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_GUARDIAN_GET_PERF_STATS: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x80C, METHOD_BUFFERED, FILE_READ_DATA);
pub const IOCTL_GUARDIAN_GET_DNS_STATS: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x80D, METHOD_BUFFERED, FILE_READ_DATA);
pub const IOCTL_GUARDIAN_SET_GUARDIAN_MODE: u32 =
    ctl_code(GUARDIAN_IOCTL_DEVICE_TYPE, 0x80E, METHOD_BUFFERED, FILE_WRITE_DATA);
